"""init

Revision ID: 6c3ef795ff2d
Revises: 
Create Date: 2025-09-16 16:06:48.414031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c3ef795ff2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clientes', 'creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas', 'estado',
               existing_type=mysql.ENUM('pendiente', 'en_revision', 'aprobada', 'rechazada', 'aprobada_auto', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'pendiente'"))
    op.alter_column('facturas', 'observaciones',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('facturas', 'creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas', 'actualizado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # op.drop_index(op.f('numero_factura'), table_name='facturas')  # Comentado para evitar error si el índice no existe
    # op.create_unique_constraint('uix_num_prov', 'facturas', ['numero_factura', 'proveedor_id'])  # Comentado para evitar error de clave duplicada
    op.alter_column('proveedores', 'creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.add_column('responsable_proveedor', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))  # Comentado para evitar error de columna duplicada
    # op.drop_index(op.f('responsable_id'), table_name='responsable_proveedor')  # Comentado para evitar error de clave foránea en MySQL
    op.create_unique_constraint('uix_resp_prov', 'responsable_proveedor', ['responsable_id', 'proveedor_id'])
    op.add_column('responsables', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('responsables', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('responsables', 'last_login',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responsables', 'last_login',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('responsables', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_column('responsables', 'creado_en')
    op.drop_constraint('uix_resp_prov', 'responsable_proveedor', type_='unique')
    op.create_index(op.f('responsable_id'), 'responsable_proveedor', ['responsable_id', 'proveedor_id'], unique=True)
    op.drop_column('responsable_proveedor', 'creado_en')
    op.alter_column('proveedores', 'creado_en',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uix_num_prov', 'facturas', type_='unique')
    op.create_index(op.f('numero_factura'), 'facturas', ['numero_factura', 'proveedor_id'], unique=True)
    op.alter_column('facturas', 'actualizado_en',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('facturas', 'creado_en',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('facturas', 'observaciones',
               existing_type=sa.String(length=2048),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('facturas', 'estado',
               existing_type=mysql.ENUM('pendiente', 'en_revision', 'aprobada', 'rechazada', 'aprobada_auto', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'pendiente'"))
    op.alter_column('clientes', 'creado_en',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('audit_log', 'creado_en',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
