"""Actualizacion bd

Revision ID: e110d55753e7
Revises: 
Create Date: 2025-09-15 23:10:22.176963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e110d55753e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('nit'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('email'), table_name='responsables')
    op.drop_index(op.f('usuario'), table_name='responsables')
    op.drop_table('responsables')
    op.drop_index(op.f('nit'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('responsable_id'), table_name='responsable_proveedor')
    op.drop_table('responsable_proveedor')
    op.drop_index(op.f('cufe'), table_name='facturas')
    op.drop_index(op.f('numero_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('entidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('entidad_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('accion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('detalle', mysql.JSON(), nullable=True),
    sa.Column('creado_en', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('facturas',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('fecha_emision', sa.DATE(), nullable=False),
    sa.Column('cliente_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('proveedor_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('subtotal', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('iva', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('moneda', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('estado', mysql.ENUM('PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'APROBADA_AUTO'), server_default=sa.text("'PENDIENTE'"), nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('observaciones', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cufe', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('total_a_pagar', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('responsable_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('aprobada_automaticamente', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('creado_por', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('creado_en', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('actualizado_en', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('facturas_ibfk_1')),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('facturas_ibfk_2')),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], name=op.f('facturas_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('numero_factura'), 'facturas', ['numero_factura', 'proveedor_id'], unique=True)
    op.create_index(op.f('cufe'), 'facturas', ['cufe'], unique=True)
    op.create_table('responsable_proveedor',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('responsable_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('proveedor_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('responsable_proveedor_ibfk_2')),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], name=op.f('responsable_proveedor_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('responsable_id'), 'responsable_proveedor', ['responsable_id', 'proveedor_id'], unique=True)
    op.create_table('proveedores',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('razon_social', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('area', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('contacto_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('creado_en', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nit'), 'proveedores', ['nit'], unique=True)
    op.create_table('responsables',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('area', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('activo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('responsables_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('usuario'), 'responsables', ['usuario'], unique=True)
    op.create_index(op.f('email'), 'responsables', ['email'], unique=True)
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('clientes',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('razon_social', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('contacto_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('creado_en', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('nit'), 'clientes', ['nit'], unique=True)
    # ### end Alembic commands ###
